### ISSUE TITLE
Error in extract(., , meta0$cell_barcode)

### ISSUE THREAD

**Issue by sshakil12** [neurorestore/Libra#12]
Hello
Thanks a lot for implementing this package!

I installed the Libra package into Rstudio and ran the demo, but seem to get this error: 

"Error in extract(., , meta0$cell_barcode) : 
  object of type 'closure' is not subsettable"

Any guidance would be much appreciated. 

Thank you,
S.

**Comment by jordansquair** [comment]
Sorry about that. Should be fixed. Just re-install.

**Comment by sshakil12** [comment]
thank you!
