### ISSUE TITLE
Accounting for covariates

### ISSUE THREAD

**Issue by smorabit** [neurorestore/Libra#25]
First off thanks for developing such a useful differential expression package! 

I am wondering if it is possible to account for covariates when running edgeR through the Libra package? For example, RNA integrity number is a technical replicate-level covariate that is often included in differential expression models. I can't see any options for this in the `run_de` function.

**Comment by jordansquair** [comment]
We haven't yet put this in. We will add it in a coming update but please feel free to submit a PR if you want it quicker!

**Comment by smorabit** [comment]
Good to hear that you will put it in an update! I ended up just writing my own function to run edgeR with covariates on the output from the `to_pseudobulk` function. Although I will note that any covariate I tried on my dataset gave me almost no significant results, so it is likely that the model is overfit...
