### ISSUE TITLE
Some Thing Wrong with DESeq2 and Limma?

### ISSUE THREAD

**Issue by hjh-air-cond** [neurorestore/Libra#31]
HI! I've been using Libra for months, but today I found something wrong with the DESeq2 and Limma.

I'm running Libra on my dataset, each condition containing 3 replicates.

But When I using Deseq2, It returns:
![图片](https://user-images.githubusercontent.com/90448222/194094320-c7e9c896-8fb1-4461-907a-e46141d1f830.png)
And When I using Limma, It returns:
![图片](https://user-images.githubusercontent.com/90448222/194094577-fc32e822-a954-444b-aa6c-05d7886ed88f.png)

Also, for now run_de() can work with edgeR. And the fun fact is the same code can work on the the other Seurat Object but not the one I'm analysing now. The difference between this dataset and others is this is bigger and containg other assays( including the 'intergrated' assay and the splicing assays for velocyto. )

Could someone offer a soulation? Thanks!

**Comment by jordansquair** [comment]
If you have multiple assays and you pass a Seurat object you need to correctly set the default assay, or else pass in the matrix directly to avoid errors.
DefaultAssay(DEG.data) = 'RNA'

**Comment by jordansquair** [comment]
Given there is no error with other datasets I do not think this is a bug with Libra.
Perhaps try passing the matrix you want to do your analysis with directly in, instead of through the Seurat object.
Alternatively, you can check the Seurat github for tutorials on assay manipulation.

**Comment by hjh-air-cond** [comment]
Sure, I will try your advice!
Thanks for all the help!
