### ISSUE TITLE
Design order and account batch effect

### ISSUE THREAD

**Issue by VergaJU** [neurorestore/Libra#32]
I am running DE analysis on some single cell datasets created merging multiple samples from different studies. All the datasets are saved as Seurat objects and the meta.data have this structure:
```                     
 orig.ident nCount_RNA nFeature_RNA percent_mt
PMM_Bcell_1_TCACAAGCACGGACAA-1        PMM       1943          813   4.220278
PMM_Bcell_4_AAGGAGCCAGGTCTCG-1        PMM       1285          733   2.101167
PMM_Bcell_4_GTGGGTCAGAACAATC-1        PMM       1111          601   2.430243
PMM_BM_3_GGACAAGGTCTAGCGC-1           PMM       3502         1592   4.625928
PMM_BM_8_CACAGGCGTGTATGGG-1           PMM       3393         1757   5.097230
PMM_BM_8_TGGCGCACAACTGCGC-1           PMM       2856         1419   4.201681
                                      label             cell_type   replicate
PMM_Bcell_1_TCACAAGCACGGACAA-1  NK resident CD56dimCD16+ NK cells PMM_Bcell_1
PMM_Bcell_4_AAGGAGCCAGGTCTCG-1 NK exhausted CD56dimCD16+ NK cells PMM_Bcell_4
PMM_Bcell_4_GTGGGTCAGAACAATC-1 NK exhausted CD56dimCD16+ NK cells PMM_Bcell_4
PMM_BM_3_GGACAAGGTCTAGCGC-1     NK resident CD56dimCD16+ NK cells    PMM_BM_3
PMM_BM_8_CACAGGCGTGTATGGG-1     NK resident CD56dimCD16+ NK cells    PMM_BM_8
PMM_BM_8_TGGCGCACAACTGCGC-1    NK exhausted CD56dimCD16+ NK cells    PMM_BM_8
```

The columns `label` contains the two groups that I want to compare, `cell_type` as the name suggest the cell types and `replicate` the different samples which the cells come from.

My questions are:
- I can I select the order of the comparison (NK exhausted vs NK resident | NK resident vs NK exhasuted)? If the answer is no, how can I understand which group is taken as control?
- To take account of the batch effect, there are different methods, for example with DESeq2 is possible to add it in the model design (~batch + condition), is it possible to add this variable to Libra's function `run_de`? If no, does it make sense to take the pseudobulk matrix and use it as bulk expression matrix to input into edgeR/DESeq2/limma? In this way I could create a personalized design matrix or run the batch correction separately before run the DE analysis

Thank you for the support
Jacopo

**Comment by jordansquair** [comment]
1) Yes you can simply set the factor levels and Libra will use that to set the reference.
2) No, we will add this in an updated version. However, you can just to Libra:::to_pseudobulk and use this in your own custom analysis with edgeR/DESeq2/limma.

**Comment by VergaJU** [comment]
Thank you for the answer, all clear

**Comment by LiMiPo** [comment]
Hi，I wanna to ask how to specify  the comparison  in Libra?

**Comment by jordansquair** [comment]
See https://github.com/neurorestore/Libra/issues/6

**Comment by LiMiPo** [comment]
> Thanks

**Comment by LiMiPo** [comment]
Hello，beforeI am running DE analysis，I set data$label <- factor(data$label, levels = c("after","before"))，does it mean that the comparison is before vs after ?

**Comment by jordansquair** [comment]
The second factor level is used as reference.

**Comment by LiMiPo** [comment]
Thanks so much
