### ISSUE TITLE
Can we speed up run_de with mixed models ? 

### ISSUE THREAD

**Issue by Nayrouz109** [neurorestore/Libra#34]
Hello, 

Quick question, is it normal for `run_DE(sc, de_family = "mixedmodel")` to take too long to run (around 24hrs) when using one of your 18 gold standard single-cell datasets. 

If so, is there a way you'd recommend using to speed it up? 

Thanks!

**Comment by skinnider** [comment]
Short answer is this is normal and we did not find a way to speed it up using this particular implementation. You might be interested in NEBULA (https://www.nature.com/articles/s42003-021-02146-6) which seems like a promising alternative.

**Comment by Nayrouz109** [comment]
ah thank you !
