### ISSUE TITLE
Error in `group_by()`: ! Must group by variables found in `.data`. ✖ Column `cell_type` is not found.

### ISSUE THREAD

**Issue by yecotoo** [neurorestore/Libra#61]
libra_result = Libra::run_de(sc, meta = NULL,
+              replicate_col = "orig.ident",
+              cell_type_col = "cell_type", 
+              label_col = "seurat_clusters",
+              de_family = 'pseudobulk',                 
+              de_method = 'edgeR', 
+              de_type = 'LRT',
+              min_cells = 3,
+              min_reps = 2,
+              input_type = "scRNA",
+              n_threads = 4
+              )
[1] "Macrophage"
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
---
Backtrace:
     ▆
  1. ├─Libra::run_de(...)
  2. │ └─... %>% ...
  3. ├─dplyr::rename(...)
  4. ├─dplyr::arrange(., cell_type, gene)
  5. ├─dplyr::ungroup(.)
  6. ├─dplyr::select(...)
  7. ├─dplyr::left_join(., out_stats, by = "gene")
  8. ├─dplyr::select(., -avg_logFC)
  9. ├─dplyr::mutate(., gene = as.character(gene))
 10. ├─dplyr::mutate(., p_val_adj = p.adjust(p_val, method = "BH"))
 11. ├─dplyr::group_by(., cell_type)
 12. └─dplyr:::group_by.data.frame(., cell_type)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.
> rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
---
Backtrace:
     ▆
  1. ├─Libra::run_de(...)
  2. │ └─... %>% ...
  3. ├─dplyr::rename(...)
  4. ├─dplyr::arrange(., cell_type, gene)
  5. ├─dplyr::ungroup(.)
  6. ├─dplyr::select(...)
  7. ├─dplyr::left_join(., out_stats, by = "gene")
  8. ├─dplyr::select(., -avg_logFC)
  9. ├─dplyr::mutate(., gene = as.character(gene))
 10. ├─dplyr::mutate(., p_val_adj = p.adjust(p_val, method = "BH"))
 11. ├─dplyr::group_by(., cell_type)
 12. └─dplyr:::group_by.data.frame(., cell_type)
 13.   └─dplyr::group_by_prepare(.data, ..., .add = .add, error_call = current_env())
 14.     └─rlang::abort(bullets, call = error_call)
 15. Still doesn't work, I tried two seuratobjects, one of them is OK, another one is not. I checked their structures, just the same！So I was confused. Please help me, thanks
 16. @AlanTeoYueYang

**Comment by yecotoo** [comment]
I thought it's a new issue of the wrapped code. Before the last update, I had tested the seuratObject A and B, A worked and give a result. B failed and showed me the error. I have checked the data structures between A and B. They were same as each other. That's why I confused, After the last update, I tried again. Just as  same as what happened before. So I thought it's a new issue of the wrapped code. What you think? Please tell me, thanks!

**Comment by AlanJimi404** [comment]
Agree, I met this error too.

**Comment by yecotoo** [comment]
> Agree, I met this error too.

I guess the identification of Cell_Type in somewhere may be wrong

**Comment by yecotoo** [comment]
> Agree, I met this error too.

I guess the identification of Cell_Type in somewhere may be wrong

**Comment by AlanTeoYueYang** [comment]
Hi, I have identified the bug and the latest push should fix it.

**Comment by yecotoo** [comment]
Thanks for your help! I will try it again now!

**Comment by yecotoo** [comment]
libra_result = Libra::run_de(sc, meta = NULL,
+              replicate_col = "orig.ident",
+              cell_type_col = "cell_type", 
+              label_col = "seurat_clusters",
+              de_family = 'pseudobulk',                 
+              de_method = 'edgeR', 
+              de_type = 'LRT',
+              min_cells = 3,
+              min_reps = 2,
+             input_type = "scRNA",
+              n_threads = 4
+              )
[1] "Macrophage"
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found. 
I tried again, Still meet the error. This time I found something deserved to explore:
cluster 0    1    2    3    4    5    7    8    9 
number 1663 2152  260  593  381   90   19   26    9 
when I compared cluster 2 and 4 in subgroup A, it worked well, however, when I changed to cluster 1 and 5, it failed again.
I suspected that the key was the quantitative difference between the two clusters.  Then I changed another subgroup B to run:
 cluster 0    1    2    3    4    5    6    7    8    9 
 number 15    6 1441  696  100   95  163  106    4   16 
in this new subgroup,  I compared cluster 2 and 9 in subgroup A, it also worked well.
I was confused again. Barely, it's not the cause of the quantitative difference between the two clusters.

**Comment by yecotoo** [comment]
> Hi, I have identified the bug and the latest push should fix it.

libra_result = Libra::run_de(sc, meta = NULL,
+              replicate_col = "orig.ident",
+              cell_type_col = "cell_type", 
+              label_col = "seurat_clusters",
+              de_family = 'pseudobulk',                  #缺陷：pseudobulk差异分析需要足够的两两比较的样本数量，否则结果会出现较强的假阴性现象。
+              de_method = 'edgeR', 
+              de_type = 'LRT',
+              min_cells = 3,
+              min_reps = 2,
+             input_type = "scRNA",
+              n_threads = 4
+              )
[1] "Macrophage"
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
---
Backtrace:
     ▆
  1. ├─Libra::run_de(...)
  2. │ └─... %>% ...
  3. ├─dplyr::rename(...)
  4. ├─dplyr::arrange(., cell_type, gene)
  5. ├─dplyr::ungroup(.)
  6. ├─dplyr::select(...)
  7. ├─dplyr::left_join(., out_stats, by = c("gene", "cell_type"))
  8. ├─dplyr::select(., -avg_logFC)
  9. ├─dplyr::mutate(., gene = as.character(gene))
 10. ├─dplyr::mutate(., p_val_adj = p.adjust(p_val, method = "BH"))
 11. ├─dplyr::group_by(., cell_type)
 12. └─dplyr:::group_by.data.frame(., cell_type)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.
> rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
---
Backtrace:
     ▆
  1. ├─Libra::run_de(...)
  2. │ └─... %>% ...
  3. ├─dplyr::rename(...)
  4. ├─dplyr::arrange(., cell_type, gene)
  5. ├─dplyr::ungroup(.)
  6. ├─dplyr::select(...)
  7. ├─dplyr::left_join(., out_stats, by = c("gene", "cell_type"))
  8. ├─dplyr::select(., -avg_logFC)
  9. ├─dplyr::mutate(., gene = as.character(gene))
 10. ├─dplyr::mutate(., p_val_adj = p.adjust(p_val, method = "BH"))
 11. ├─dplyr::group_by(., cell_type)
 12. └─dplyr:::group_by.data.frame(., cell_type)
 13.   └─dplyr::group_by_prepare(.data, ..., .add = .add, error_call = current_env())
 14.     └─rlang::abort(bullets, call = error_call)
 15. Hello! It's the new error remind, hope it can help you to fix it!

**Comment by yecotoo** [comment]
I just tested cluster2 and 3，2 and 0 in subgroupA, all failed, seems only  cluster2 and 4 in subgroupA successed.

**Comment by AlanTeoYueYang** [comment]
Hi, can you send me your data at yueyang.teo@epfl.ch?

**Comment by yecotoo** [comment]
OK

**Comment by yecotoo** [comment]
> Hi, can you send me your data at [yueyang.teo@epfl.ch](mailto:yueyang.teo@epfl.ch)?

Hello! the test data has been sent to your emailbox, thanks!

**Comment by AlanTeoYueYang** [comment]
Hi, I identified the issue for the data you sent.
```
sc@meta.data %>% dplyr::select(orig.ident, seurat_clusters) %>% table()
              seurat_clusters
orig.ident        5    1
  3dpi_sample1    0 2152
  3dpi_sample2   90    0
```
Seems like you are only have 2 replicates (1 replicate per condition) and the min.rep is set at 2

**Comment by yecotoo** [comment]
> 您好，我发现了您发送的数据存在问题。
> 
> ```
> sc@meta.data %>% dplyr::select(orig.ident, seurat_clusters) %>% table()
>               seurat_clusters
> orig.ident        5    1
>   3dpi_sample1    0 2152
>   3dpi_sample2   90    0
> ```
> 
> 似乎您只有 2 个仿行（每个条件 1 个仿行），并且 min.rep 设置为 2，这意味着每个条件至少需要 2 个仿行

thanks for your reply! I tried it by using "min.rep = 1", unfortunately, it didn't work and some thing new happened.
libra_result = Libra::run_de(sc, meta = NULL,
+              replicate_col = "orig.ident",
+              cell_type_col = "cell_type", 
+              label_col = "seurat_clusters",
+              de_family = 'pseudobulk',                 
+              de_method = 'edgeR', 
+              de_type = 'LRT',
+              min_cells = 3,
+              min_reps = 1,
+             input_type = "scRNA",
+              n_threads = 4
+              )
[1] "Macrophage"
Error in `map()`:
ℹ In index: 1.
ℹ With name: Macrophage.
Caused by error in `glmFit.default()`:
! NA dispersions not allowed
Run `rlang::last_trace()` to see where the error occurred.
警告信息:
In estimateDisp.default(y = y$counts, design = design, group = group,  :
  No residual df: setting dispersion to NA
> rlang::last_trace()
<error/purrr_error_indexed>
Error in `map()`:
ℹ In index: 1.
ℹ With name: Macrophage.
Caused by error in `glmFit.default()`:
! NA dispersions not allowed
---
Backtrace:
     ▆
  1. └─Libra::run_de(...)
  2.   └─Libra:::pseudobulk_de(...)
  3.     └─purrr::map(...)
  4.       └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  5.         ├─purrr:::with_indexed_errors(...)
  6.         │ └─base::withCallingHandlers(...)
  7.         ├─purrr:::call_with_cleanup(...)
  8.         └─Libra (local) .f(.x[[i]], ...)
  9.           └─base::tryCatch(...)
 10.             └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 11.               └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 12.                 └─value[[3L]](cond)
 13.                   └─base::message(e)
 14.                     ├─base::withRestarts(...)
 15.                     │ └─base (local) withOneRestart(expr, restarts[[1L]])
 16.                     │   └─base (local) doWithOneRestart(return(expr), restart)
 17.                     └─base::signalCondition(cond)
Run rlang::last_trace(drop = FALSE) to see 3 hidden frames.
> rlang::last_trace(drop = FALSE)
<error/purrr_error_indexed>
Error in `map()`:
ℹ In index: 1.
ℹ With name: Macrophage.
Caused by error in `glmFit.default()`:
! NA dispersions not allowed
---
Backtrace:
     ▆
  1. ├─Libra::run_de(...)
  2. │ └─Libra:::pseudobulk_de(...)
  3. │   └─purrr::map(...)
  4. │     └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  5. │       ├─purrr:::with_indexed_errors(...)
  6. │       │ └─base::withCallingHandlers(...)
  7. │       ├─purrr:::call_with_cleanup(...)
  8. │       └─Libra (local) .f(.x[[i]], ...)
  9. │         └─base::tryCatch(...)
 10. │           └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 11. │             └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 12. │               └─value[[3L]](cond)
 13. │                 └─base::message(e)
 14. │                   ├─base::withRestarts(...)
 15. │                   │ └─base (local) withOneRestart(expr, restarts[[1L]])
 16. │                   │   └─base (local) doWithOneRestart(return(expr), restart)
 17. │                   └─base::signalCondition(cond)
 18. └─purrr (local) `<fn>`(`<smplErrr>`)
 19.   └─cli::cli_abort(...)
 20.     └─rlang::abort(...)
 21. 
Honestly, I don't think it's the keypoint (min.rep = 2).  I compared cluster 2 and 4 in subgroup A, it worked well under "min.rep = 2"
I will send you the data of cluster 2 and 4 in subgroup A for test. Hope it can help you, thanks!

**Comment by AlanTeoYueYang** [comment]
Hi, so to briefly explain the issue, you do not have enough replicates to perform DE that Libra is design to do. The model cannot estimate dispersions because there is only 1 count value for each label (once you perform pseudobulking). I advise against performing differential gene expression with single-cell data with only 1 replicate per label.

**Comment by yecotoo** [comment]
Thank you very much! I got you. Best wishes!

**Comment by yecotoo** [comment]
> 嗨，简单解释一下这个问题，您没有足够的重复来执行 Libra 旨在执行的 DE。该模型无法估计离差，因为每个标签只有 1 个计数值（执行伪膨胀后）。我建议不要使用每个标记只有 1 个重复的单细胞数据进行差异基因表达。它适用于其他数据集，因为我假设每个标签至少有 2 个重复。

Sorry to bother you! I changed the method, something new happens, I don't know why it tells me "Column `pct.1` doesn't exist."  Is it a new error in the wrapped codes? Thanks!
libra_result = Libra::run_de(sc, meta = NULL,
+              replicate_col = "orig.ident",
+              cell_type_col = "cell_type", 
+              label_col = "seurat_clusters",
+              de_family = 'singlecell',                 
+              de_method = 'wilcox',
+              #de_type = 'LRT',
+              #min_cells = 3,
+              #min_reps = 2,
+             input_type = "scRNA",
+              n_threads = 4
+              )
Normalizing layer: counts
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1/1] working on cell type: Macrophage ...
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `pct.1` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `pct.1` doesn't exist.
---
Backtrace:
    ▆
 1. ├─Libra::run_de(...)
 2. │ └─... %>% ...
 3. ├─dplyr::rename(...)
 4. ├─dplyr::arrange(., cell_type, gene)
 5. ├─dplyr::ungroup(.)
 6. ├─dplyr::select(...)
 7. └─dplyr:::select.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 17 hidden frames.
> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `pct.1` doesn't exist.
---
Backtrace:
    ▆
 1. ├─Libra::run_de(...)
 2. │ └─... %>% ...
 3. ├─dplyr::rename(...)
 4. ├─dplyr::arrange(., cell_type, gene)
 5. ├─dplyr::ungroup(.)
 6. ├─dplyr::select(...)
 7. └─dplyr:::select.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 17 hidden frames.
