### ISSUE TITLE
Column pct.1 doesn't exist

### ISSUE THREAD

**Issue by yecotoo** [neurorestore/Libra#62]
Hi! Sorry to bother you. I changed the method, something new happens, I don't know why it tells me "Column pct.1 doesn't exist." Is it a new error in the wrapped codes? Thanks!
libra_result = Libra::run_de(sc, meta = NULL,

         replicate_col = "orig.ident",
         cell_type_col = "cell_type", 
         label_col = "seurat_clusters",
         de_family = 'singlecell',                 
         de_method = 'wilcox',
         #de_type = 'LRT',
         #min_cells = 3,
         #min_reps = 2,
        input_type = "scRNA",
         n_threads = 4
         )
Normalizing layer: counts
Performing log-normalization
0% 10 20 30 40 50 60 70 80 90 100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1/1] working on cell type: Macrophage ...
Error in dplyr::select():
! Can't select columns that don't exist.
✖ Column pct.1 doesn't exist.
Run rlang::last_trace() to see where the error occurred.

rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in dplyr::select():
! Can't select columns that don't exist.
✖ Column pct.1 doesn't exist.

Backtrace:
▆

├─Libra::run_de(...)
│ └─... %>% ...
├─dplyr::rename(...)
├─dplyr::arrange(., cell_type, gene)
├─dplyr::ungroup(.)
├─dplyr::select(...)
└─dplyr:::select.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 17 hidden frames.
rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in dplyr::select():
! Can't select columns that don't exist.
✖ Column pct.1 doesn't exist.

Backtrace:
▆

├─Libra::run_de(...)
│ └─... %>% ...
├─dplyr::rename(...)
├─dplyr::arrange(., cell_type, gene)
├─dplyr::ungroup(.)
├─dplyr::select(...)
└─dplyr:::select.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 17 hidden frames.

**Comment by AlanTeoYueYang** [comment]
Hi, apologies for that bug. It should be fixed now.

**Comment by yecotoo** [comment]
> Hi, apologies for that bug. It should be fixed now.

It run well. Thanks!
